language: node_js
dist: trusty
node_js:
- 8
- 10
services:
- postgresql
addons:
  postgresql: '10'
  apt:
    update: true
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - postgresql-10
    - postgresql-client-10
before_script:
- psql -c "CREATE DATABASE test1 LC_COLLATE 'en_US.UTF-8';" -U postgres
- psql -c "CREATE DATABASE test2 LC_COLLATE 'en_US.UTF-8';" -U postgres
- psql -c "CREATE DATABASE demo LC_COLLATE 'en_US.UTF-8';" -U postgres
- npm run db-build
env:
- PGPORT=5433
- PG_URL=postgres://postgres@localhost:5433/ CXX=g++-4.8
notifications:
  email: false
deploy:
  provider: npm
  email: lacooljay@gmail.com
  api_key:
    secure: EHe3N7aQb2TcQRbjxdsyQDCNavm/aqFJq27ws5lmu0s0z1OktJ2bg+3Pa4ExuCr1WMBAz4u7KvTitOkboVvXE6XSu2FCABNQQTxWKLobvUgxaonZhX50eSG2VcoBUmktsjBhQPDAQ5F5gWlDZuk+iQ+5p3yD9K2APLMtV/5ni96mMNgMfoz7KsoDg46ziqoWE2UH0nHd7WKQbevEazGirrLHXTc50COY+qGFOm0I5V3sFqzGXTmkzmGkEcxDbIJH3aPwy9ywbmdi83xi9ftIrd5vB89a/Iabkd5gTTOSEJFSiNplhISJKumaB4EEqolpBiuyjSSna/ID4eMll5n3RIScUhCTgUYW+8BjfWxb136iqopfXP6wJtIYQympj4ljPa89keiwjyJKIM6AHuBaNkLfzbTWLPC63zQ0URCpChgSCcp/RQX0loHETgCSk77ghxIPA4q8mr+NHJWRKhhMwoZhds/LCFucDKrs12KAEG7O6dPZ+1m1HEKdPs3b4OVmDuLQk5cNs7UXADvuflO90TIpLVWytvwF6zLIoQFhLBJ2ladzSo9xpxWAjeTPE6Hcc9kIaQopzWLqjFMUk34K9TJ1Kflmo67Njgk0D7Eictb29ACch1qhEQ7YBM3a+IRwHVV4+icQCPOmccG+UOHywnsb9L8QduFgF2VNrl05ISE=
  on:
    repo: dhenson02/join-monster
